ALTER TABLE "app_settings" ALTER COLUMN "watchlist" SET DEFAULT '[{"symbol":"AAPL","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"MSFT","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"AMZN","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"GOOGL","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"META","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"TSLA","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"NVDA","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"AMD","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"AVGO","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"BE","exchange":"NYSE","automaticScanEnabled":true},{"symbol":"MU","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"SKHY","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"SNDK","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"NOW","exchange":"NYSE","automaticScanEnabled":true},{"symbol":"CRM","exchange":"NYSE","automaticScanEnabled":true},{"symbol":"SPCX","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"ORCL","exchange":"NYSE","automaticScanEnabled":true},{"symbol":"GLD","exchange":"AMEX","automaticScanEnabled":true},{"symbol":"SLV","exchange":"AMEX","automaticScanEnabled":true},{"symbol":"USO","exchange":"AMEX","automaticScanEnabled":true}]'::jsonb;--> statement-breakpoint
ALTER TABLE "app_settings" ALTER COLUMN "daily_budget_usd" SET DEFAULT '12.00';--> statement-breakpoint
UPDATE "app_settings"
SET
	"watchlist" = '[{"symbol":"AAPL","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"MSFT","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"AMZN","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"GOOGL","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"META","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"TSLA","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"NVDA","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"AMD","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"AVGO","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"BE","exchange":"NYSE","automaticScanEnabled":true},{"symbol":"MU","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"SKHY","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"SNDK","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"NOW","exchange":"NYSE","automaticScanEnabled":true},{"symbol":"CRM","exchange":"NYSE","automaticScanEnabled":true},{"symbol":"SPCX","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"ORCL","exchange":"NYSE","automaticScanEnabled":true},{"symbol":"GLD","exchange":"AMEX","automaticScanEnabled":true},{"symbol":"SLV","exchange":"AMEX","automaticScanEnabled":true},{"symbol":"USO","exchange":"AMEX","automaticScanEnabled":true}]'::jsonb,
	"updated_at" = now()
WHERE "watchlist" = '[{"symbol":"AAPL","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"MSFT","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"NVDA","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"AMZN","exchange":"NASDAQ","automaticScanEnabled":true},{"symbol":"GOOGL","exchange":"NASDAQ","automaticScanEnabled":true}]'::jsonb;--> statement-breakpoint
UPDATE "app_settings"
SET "daily_budget_usd" = '12.00', "updated_at" = now()
WHERE "daily_budget_usd" = '10.00';
