import { z } from "zod";
import { auth } from "@/auth";
import { isAuthorizedSession } from "@/auth/authorization";
import { activateGexTemplate, getGexTemplateContent, getGexTemplates, saveGexTemplate } from "@/gex/repository";
import { findGexTemplateBoundary } from "@/gex/template-boundary";
export const runtime = "nodejs";
const headers = { "Cache-Control": "private, no-store" };
const schema = z.object({ kind: z.enum(["engine", "scanner"]), content: z.string().min(1).max(200_000).refine((value) => findGexTemplateBoundary(value) >= 0, "Add a Step 2 heading (for example, # STEP 2 or # 2.) before the code that should remain unchanged.") }).strict();
export async function GET(request: Request) { if (!isAuthorizedSession(await auth())) return Response.json({ error: "Unauthorized" }, { status: 401, headers }); const id = new URL(request.url).searchParams.get("id"); const kind = new URL(request.url).searchParams.get("kind"); if (id || kind) { const parsed = z.object({ id: z.string().uuid(), kind: z.enum(["engine", "scanner"]) }).safeParse({ id, kind }); if (!parsed.success) return Response.json({ error: "Invalid template." }, { status: 400, headers }); const template = await getGexTemplateContent(parsed.data.kind, parsed.data.id); if (!template) return Response.json({ error: "Template not found." }, { status: 404, headers }); return new Response(template.content, { headers: { ...headers, "Content-Type": "text/plain; charset=utf-8", "Content-Disposition": `attachment; filename=\"${parsed.data.kind}-template-v${template.version}.txt\"` } }); } return Response.json({ templates: await getGexTemplates() }, { headers }); }
export async function POST(request: Request) { if (!isAuthorizedSession(await auth())) return Response.json({ error: "Unauthorized" }, { status: 401, headers }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: parsed.error.issues[0]?.message ?? "Choose a non-empty .txt template smaller than 200 KB." }, { status: 400, headers }); try { await saveGexTemplate(parsed.data.kind, parsed.data.content); return Response.json({ templates: await getGexTemplates() }, { headers }); } catch { return Response.json({ error: "The template could not be saved. Please try again." }, { status: 500, headers }); } }
export async function PATCH(request: Request) { if (!isAuthorizedSession(await auth())) return Response.json({ error: "Unauthorized" }, { status: 401, headers }); try { const body = z.object({ kind: z.enum(["engine", "scanner"]), id: z.string().uuid() }).parse(await request.json()); await activateGexTemplate(body.kind, body.id); return Response.json({ templates: await getGexTemplates() }, { headers }); } catch { return Response.json({ error: "That saved template is no longer available. Refresh and choose another version." }, { status: 400, headers }); } }
